ci:
    autoupdate_schedule: monthly
    autofix_prs: true
    skip: [mypy, pylint, dm-generate-all, dependencies, verdi-autodocs]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
        exclude: &exclude_pre_commit_hooks >
            (?x)^(
                tests/.*(?<!\.py)$|
                docs/source/.+\.aiida/repo/.+|
            )$
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        exclude: *exclude_pre_commit_hooks
    -   id: check-yaml


-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

-   repo: https://github.com/ikamensh/flynt/
    rev: '0.76'
    hooks:
    -   id: flynt
        args: [
            '--line-length=120',
            '--fail-on-change',
        ]

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.32.0
    hooks:
    -   id: yapf
        name: yapf
        types: [python]
        exclude: &exclude_files >
            (?x)^(
                docs/.*|
            )$
        args: ['-i']
        additional_dependencies: ['toml']

-   repo: local

    hooks:

    -   id: imports
        name: imports
        entry: python utils/make_all.py
        language: python
        types: [python]
        require_serial: true
        pass_filenames: false
        files: aiida/.*py

    -   id: mypy
        name: mypy
        entry: mypy
        args: [--config-file=pyproject.toml]
        language: python
        types: [python]
        require_serial: true
        pass_filenames: true

    -   id: pylint
        name: pylint
        entry: pylint
        types: [python]
        language: system
