[tool.flynt]
line-length = 120
fail-on-change = true

[tool.isort]
force_sort_within_sections = true
include_trailing_comma = true
line_length = 120
multi_line_output = 3

[tool.pylint.format]
max-line-length = 120

[tool.pylint.messages_control]
disable = [
    'cyclic-import',
    'duplicate-code',
    'import-outside-toplevel',
    'inconsistent-return-statements',
    'locally-disabled',
    'logging-fstring-interpolation',
    'no-else-raise',
    'raise-missing-from',
    'too-few-public-methods',
    'too-many-ancestors',
    'too-many-locals',
    'too-many-branches',
    'too-many-statements',
    'too-many-arguments',
    'too-many-instance-attributes',
    'not-context-manager',
]

[tool.pylint.basic]
good-names = [
    'x',
    'y',
    'z',
    'i',
    'j',
    'k',
    'dt',
    'pk',
    'fg',
    'tz',
    'nl',
    'TemplatereplacerCalculation',
    'ArithmeticAddCalculation',
    'MultiplyAddWorkChain'
]
docstring-min-length = 5

[tool.pylint.design]
max-locals = 20

[tool.yapf]
align_closing_bracket_with_visual_indent = true
based_on_style = 'google'
coalesce_brackets = true
column_limit = 120
dedent_closing_brackets = true
indent_dictionary_value = false
split_arguments_when_comma_terminated = true
